apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: trinityid
  labels:
    app: keycloak
    component: oidc
spec:
  type: ClusterIP
  selector:
    app: keycloak
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
