---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir-alertmanager
  namespace: mimir
  labels:
    app: mimir-alertmanager
    component: alertmanager
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mimir-alertmanager
  template:
    metadata:
      labels:
        app: mimir-alertmanager
        component: alertmanager
    spec:
      serviceAccountName: mimir-alertmanager
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        fsGroup: 10001
      containers:
      - name: alertmanager
        image: grafana/mimir:2.10.0
        imagePullPolicy: IfNotPresent
        args:
          - -target=alertmanager
          - -config.file=/etc/mimir/mimir.yaml
          - -alertmanager.storage.path=/data
          - -alertmanager.web.external-url=http://alertmanager:9093/alertmanager
        ports:
        - name: http-metrics
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 9095
          protocol: TCP
        - name: memberlist
          containerPort: 7946
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http-metrics
          initialDelaySeconds: 45
          timeoutSeconds: 1
          periodSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        volumeMounts:
        - name: config
          mountPath: /etc/mimir
        - name: data
          mountPath: /data
        - name: tmp
          mountPath: /tmp
        env:
        # Tempo/OpenTelemetry tracing configuration
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo-distributor.observability.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_SERVICE_NAME
          value: "mimir-alertmanager"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=mimir-alertmanager,service.version=2.10.0,deployment.environment=production"
        - name: OTEL_EXPORTER_OTLP_INSECURE
          value: "true"
        # Optional: Batch span processor settings for better performance
        - name: OTEL_BSP_MAX_EXPORT_BATCH_SIZE
          value: "512"
        - name: OTEL_BSP_EXPORT_TIMEOUT
          value: "30s"
        - name: OTEL_BSP_SCHEDULE_DELAY
          value: "5s"
      volumes:
      - name: config
        configMap:
          name: mimir-config
      - name: data
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - mimir-alertmanager
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: mimir-alertmanager
  namespace: mimir
  labels:
    app: mimir-alertmanager
spec:
  type: ClusterIP
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  - name: memberlist
    port: 7946
    targetPort: memberlist
    protocol: TCP
  selector:
    app: mimir-alertmanager

---
apiVersion: v1
kind: Service
metadata:
  name: mimir-alertmanager-headless
  namespace: mimir
  labels:
    app: mimir-alertmanager
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: http-metrics
    port: 8080
    targetPort: http-metrics
    protocol: TCP
  - name: grpc
    port: 9095
    targetPort: grpc
    protocol: TCP
  - name: memberlist
    port: 7946
    targetPort: memberlist
    protocol: TCP
  selector:
    app: mimir-alertmanager

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mimir-alertmanager
  namespace: mimir