apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml.template: |
    multitenancy_enabled: false

    common:
      storage:
        backend: s3
        s3:
          endpoint: ${S3_ENDPOINT}
          insecure: ${S3_SECURE_CONNECT}
          bucket_name: ${MIMIR_S3_BUCKET_NAME}
          access_key_id: ${S3_ACCESS_KEY}
          secret_access_key: ${S3_SECRET_KEY}
          signature_version: v4

    blocks_storage:
      backend: s3
      s3:
        endpoint: ${S3_ENDPOINT}
        insecure: ${S3_SECURE_CONNECT}
        bucket_name: ${MIMIR_S3_BLOCKS_BUCKET_NAME}
        access_key_id: ${S3_ACCESS_KEY}
        secret_access_key: ${S3_SECRET_KEY}
        signature_version: v4
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester:
      ring:
        kvstore:
          store: memberlist
        replication_factor: 3

    ruler:
      enable_api: true
      alertmanager_url: http://alertmanager.observability.svc.cluster.local:9093
      ring:
        kvstore:
          store: memberlist
      rule_path: /etc/mimir/rules

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
      log_level: info #TODO: remove comment
      log_format: logfmt #TODO: remove comment

    store_gateway:
      sharding_ring:
        replication_factor: 3
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - mimir-memberlist

    frontend:
      scheduler_address: "mimir-query-scheduler:9095"
      
    frontend_worker:
      scheduler_address: "mimir-query-scheduler:9095"
      frontend_address: ""

    query_scheduler:
      service_discovery_mode: dns
      max_outstanding_requests_per_tenant: 100
      ring:
        kvstore:
          store: memberlist   
 
    tracing:
      type: otel
      otel:
        otlp:
          endpoint: tempo-distributor.observability.svc.cluster.local:4317
          insecure: true
          timeout: 10s
        resource_attributes:
          service.name: mimir-alertmanager
          service.version: 2.10.0
          deployment.environment: production
        batch:
          timeout: 1s
          send_batch_size: 1024
          send_batch_max_size: 2048

    alertmanager:
      # Data directory - using ephemeral storage since config is in object storage
      data_dir: /data
      
      # How frequently to poll Alertmanager configs, default 15s
      # Set to 900 as changes are infrequent
      poll_interval: 900s 
      
      # External URL for Alertmanager UI
      external_url: ${MIMIR_ALERTMANAGER_EXTERNAL_URL}
      web:
        external_url: ${MIMIR_ALERTMANAGER_EXTERNAL_URL}

      sharding_ring:
        kvstore:
          store: memberlist
        replication_factor: 3
        heartbeat_period: 5s
        heartbeat_timeout: 1m

      # Enable clustering
      cluster:
        enabled: true
        peers: []
        peer_timeout: 15s
        gossip_interval: 200ms
        pushpull_interval: 60s
        
      # Retention for resolved alerts (kept in memory/local storage)
      retention: 120h

    alertmanager_storage:
      backend: s3
      s3:
        endpoint: ${S3_ENDPOINT}
        insecure: ${S3_SECURE_CONNECT}
        bucket_name: ${MIMIR_ALERTMANAGER_BUCKET_NAME}
        access_key_id: ${S3_ACCESS_KEY}
        secret_access_key: ${S3_SECRET_KEY}
        signature_version: v4

    limits:
      max_query_parallelism: 16
      compactor_blocks_retention_period: 15d
      
      alertmanager_max_config_size_bytes: 1048576
      alertmanager_max_templates_count: 100
      alertmanager_max_template_size_bytes: 16384
      alertmanager_max_dispatchers_per_tenant: 100
      alertmanager_max_alerts_count: 100000
      alertmanager_max_alerts_size_bytes: 104857600