---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-data-pv
  namespace: vaultwarden
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vaultwarden-data-storage
  nfs:
    path: /data/nfs/vaultwarden-data
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vaultwarden-backup-pv
  namespace: vaultwarden
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vaultwarden-backup-storage
  nfs:
    path: /data/nfs/vaultwarden-backup
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1

