---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vaultwarden-tls
  namespace: vaultwarden
spec:
  secretName: vaultwarden-tls
  dnsNames:
    - vaultwarden.tommahs.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer