apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vaultwarden
resources:
  - 00-namespace.yaml
  - 01-persistent-volumes.yaml
  - 02-persistent-volume-claims.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 05-ingress-route.yaml
  - 06-backup-cronjob.yaml
  - 10-certificate.yaml
  - 10-ingress-middleware.yaml