---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tempo-tls
  namespace: observability
spec:
  secretName: tempo-tls
  dnsNames:
    - tempo.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer