# tempo/ingress-patch.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tempo-read
  namespace: observability
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`PLACEHOLDER_TEMPO_READ_ENDPOINT`)
      priority: 10
      services:
        - kind: Service
          name: tempo-query-frontend
          namespace: observability
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
  tls:
    secretName: tempo-read-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tempo-write
  namespace: observability
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`PLACEHOLDER_TEMPO_WRITE_ENDPOINT`)
      priority: 10
      services:
        - kind: Service
          name: tempo-distributor
          namespace: observability
          passHostHeader: true
          port: 8080
          responseForwarding:
            flushInterval: 1ms
  tls:
    secretName: tempo-write-tls