# tempo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - distributor.yaml
  - ingester.yaml
  - querier.yaml
  - query-frontend.yaml
  - compactor.yaml
  - ingress.yaml
  - secret.yaml

replacements:
  # Existing replacements
  - source:
      kind: Secret
      name: tempo-secret
      fieldPath: stringData.TEMPO_READ_ENDPOINT
    targets:
      - select:
          kind: Ingress
          name: tempo
        fieldPaths:
          - "spec.rules.0.host"
  - source:
      kind: Secret
      name: tempo-secret
      fieldPath: stringData.TEMPO_WRITE_ENDPOINT
    targets:
      - select:
          kind: Ingress
          name: tempo
        fieldPaths:
          - "spec.rules.0.host"

patches:
  - path: ingress-patch.yaml