# tempo/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - distributor.yaml
  - ingester.yaml
  - querier.yaml
  - query-frontend.yaml
  - compactor.yaml
  - ingress.yaml
  - secret.yaml