---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mimir-tls
  namespace: observability
spec:
  secretName: mimir-tls
  dnsNames:
    - mimir.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer