apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml.template: |
    multitenancy_enabled: false

    common:
      storage:
        backend: s3
        s3:
          endpoint: ${S3_ENDPOINT}
          insecure: ${S3_SECURE_CONNECT}
          bucket_name: ${MIMIR_S3_BUCKET_NAME}
          access_key_id: ${S3_ACCESS_KEY}
          secret_access_key: ${S3_SECRET_KEY}
          signature_version: v4

    blocks_storage:
      backend: s3
      s3:
        endpoint: ${S3_ENDPOINT}
        insecure: ${S3_SECURE_CONNECT}
        bucket_name: ${MIMIR_S3_BLOCKS_BUCKET_NAME}
        access_key_id: ${S3_ACCESS_KEY}
        secret_access_key: ${S3_SECRET_KEY}
        signature_version: v4
      bucket_store:
        sync_dir: /tmp/mimir/tsdb-sync

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist

    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 3

    ruler:
      enable_api: true
      alertmanager_url: http://alertmanager.observability.svc.cluster.local:9093
      ring:
        kvstore:
          store: memberlist
      rule_path: /etc/mimir/rules

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095

    store_gateway:
      sharding_ring:
        replication_factor: 3
        kvstore:
          store: memberlist

    memberlist:
      join_members:
        - mimir-memberlist

    frontend:
      ring:
        kvstore:
          store: memberlist

    query_scheduler:
      max_outstanding_requests_per_tenant: 100
      ring:
        kvstore:
          store: memberlist
    limits:
      max_query_parallelism: 16
