apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
data:
  mimir.yaml: |
    multitenancy_enabled: false
    
    blocks_storage:
      backend: s3
      s3:
        endpoint: ${S3_ENDPOINT}
        insecure: ${S3_SECURE_CONNECT}
        bucket_name: ${MIMIR_S3_BUCKET_NAME}
        access_key_id: ${S3_ACCESS_KEY}
        secret_access_key: ${S3_SECRET_KEY}
        signature_version: v4
        s3forcepathstyle: ${S3_PATH_STYLE}  # Enable path-style access if required

    compactor:
      data_dir: /tmp/mimir/compactor
      sharding_ring:
        kvstore:
          store: memberlist
    
    distributor:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
    
    ingester:
      ring:
        instance_addr: 127.0.0.1
        kvstore:
          store: memberlist
        replication_factor: 3
      lifecycler:
        join_after: 0s
        observe_period: 0s
        final_sleep: 0s
        num_tokens: 512
    
    ruler:
      enable_api: true
      alertmanager_url: http://alertmanager.monitoring.svc.cluster.local:9093
      ring:
        kvstore:
          store: memberlist
      rule_path: /etc/mimir/rules
      storage:
        type: s3
        s3:
          endpoint: ${S3_ENDPOINT}
          bucket_name: ${MIMIR_S3_RULER_BUCKET_NAME}
          access_key_id: ${S3_ACCESS_KEY}
          secret_access_key: ${S3_SECRET_KEY}
          insecure: ${S3_SECURE_CONNECT}
          s3forcepathstyle: ${S3_PATH_STYLE}  # Enable path-style access for ruler data

    server:
      http_listen_port: 8080
      grpc_listen_port: 9095
    
    store_gateway:
      sharding_ring:
        replication_factor: 3
        kvstore:
          store: memberlist
    
    memberlist:
      join_members:
        - mimir-memberlist
    
    query_scheduler:
      service_discovery:
        type: dns
        dns:
          address: mimir-querier.monitoring.svc.cluster.local:8080

    limits:
      max_query_parallelism: 16
      max_query_length: 2160h
