# mimir/ingester.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mimir-ingester
spec:
  replicas: 3
  serviceName: mimir-ingester
  selector:
    matchLabels:
      app: mimir
      component: ingester
  template:
    metadata:
      labels:
        app: mimir
        component: ingester
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:2.10.3
        args:
        - -target=ingester
        - -config.file=/etc/mimir/mimir.yaml
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - name: mimir-config
          mountPath: /etc/mimir
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-ingester
spec:
  ports:
  - port: 8080
    name: http
  - port: 9095
    name: grpc
  clusterIP: None
  selector:
    app: mimir
    component: ingester