# mimir/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - memberlist.yaml
  - distributor.yaml
  - ingester.yaml
  - querier.yaml
  - query-frontend.yaml
  - query-scheduler.yaml
  - store-gateway.yaml
  - compactor.yaml
  - ruler.yaml
  - ingress.yaml
  - secret.yaml

replacements:
  - source:
      kind: Secret
      name: mimir-secret
      fieldPath: stringData.MIMIR_ENDPOINT
    targets:
    - select:
        kind: IngressRoute
        name: grafana
      fieldPaths:
      - spec.routes.0.match
      options:
        delimiter: "`"
        index: 1
    - select:
        kind: Certificate
        name: mimir-tls
      fieldPaths:
      - spec.dnsNames.0