# mimir/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - distributor.yaml
  - ingester.yaml
  - querier.yaml
  - query-frontend.yaml
  - store-gateway.yaml
  - compactor.yaml
  - ruler.yaml
  - ingress.yaml
  - secret.yaml

vars:
  - name: MIMIR_READ_ENDPOINT
    objref:
      kind: Secret
      name: lgtm-ingress-secret.yaml
      apiVersion: v1
    fieldref:
      fieldpath: data.MIMIR_READ_ENDPOINT
  - name: MIMIR_WRITE_ENDPOINT
    objref:
      kind: Secret
      name: lgtm-ingress-secret.yaml
      apiVersion: v1
    fieldref:
      fieldpath: data.MIMIR_WRITE_ENDPOINT
      
patchesStrategicMerge:
  - ingress-patch.yaml

