{
 "title": "General overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ceph_instances",
    "label": "ceph_instances",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"ceph1|ceph2|ceph3\"},instance)"
    }
   },
   {
    "name": "k8s_instances",
    "label": "K8s_instances",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"master-k8s-1|master-k8s-3|master-k8s-2|worker-k8s-1|worker-k8s-2|worker-k8s-3|worker-k8s-4|worker-k8s-5|worker-k8s-6|worker-k8s-ram1\"},instance)"
    }
   },
   {
    "name": "hv_instances",
    "label": "Hypervisor instances",
    "query": {
     "query": "label_values(node_uname_info{instance!~\"$ceph_instances|$k8s_instances\"},instance)"
    }
   },
   {
    "name": "cephcluster",
    "label": "Ceph cluster health",
    "query": {
     "query": "label_values(ceph_health_status,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Glance - VMS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))))"
      }
     ]
    },
    {
     "title": "Sys Load",
     "type": "stat",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (count(count(node_cpu_seconds_total) by (cpu)))"
      }
     ]
    },
    {
     "title": "MAX RAM Used",
     "type": "stat",
     "description": "Non available RAM memory",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100\n)",
       "legendFormat": " "
      }
     ]
    },
    {
     "title": "SWAP Used",
     "type": "stat",
     "description": "Used Swap",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  ((node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes) * 100\n)"
      }
     ]
    },
    {
     "title": "Root FS Used",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  100 - (node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\"}\n)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Quick - Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy - HV",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by ()(100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$hv_instances\"}[$__rate_interval]))) )"
      }
     ]
    },
    {
     "title": "Sys Load - HV",
     "type": "stat",
     "description": "System load  over all CPU cores together for hypervisor instances\n",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(node_load1{instance=~\"$hv_instances\"}[5m])) * 100 / \nmax(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{instance=~\"$hv_instances\"})))"
      }
     ]
    },
    {
     "title": "RAM Used - HV",
     "type": "stat",
     "description": "Non available RAM memory",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () ((1 - (node_memory_MemAvailable_bytes{instance=~\"$hv_instances\"} / node_memory_MemTotal_bytes{instance=~\"$hv_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "SWAP Used - HV",
     "type": "stat",
     "description": "Used Swap",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (((node_memory_SwapTotal_bytes{instance=~\"$hv_instances\"} - node_memory_SwapFree_bytes{instance=~\"$hv_instances\"}) / (node_memory_SwapTotal_bytes{instance=~\"$hv_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "Root FS Used  - HV",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  100 - (node_filesystem_avail_bytes{instance=~\"$hv_instances\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$hv_instances\",mountpoint=\"/\",fstype!=\"rootfs\"}\n)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Quick - ObjectStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy - ObjectStore",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by ()(100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$ceph_instances\"}[$__rate_interval]))) )"
      }
     ]
    },
    {
     "title": "Sys Load - ObjectStore",
     "type": "stat",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(node_load1{instance=~\"$ceph_instances\"}[5m])) * 100 / \nmax(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{instance=~\"$ceph_instances\"})))"
      }
     ]
    },
    {
     "title": "RAM Used - ObjectStore",
     "type": "stat",
     "description": "Non available RAM memory",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () ((1 - (node_memory_MemAvailable_bytes{instance=~\"$ceph_instances\"} / node_memory_MemTotal_bytes{instance=~\"$ceph_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "SWAP Used - ObjectStore",
     "type": "stat",
     "description": "Used Swap",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (((node_memory_SwapTotal_bytes{instance=~\"$ceph_instances\"} - node_memory_SwapFree_bytes{instance=~\"$ceph_instances\"}) / (node_memory_SwapTotal_bytes{instance=~\"$ceph_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "Root FS Used  - ObjectStore",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  100 - (node_filesystem_avail_bytes{instance=~\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"}\n)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "Quick - k8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy - k8s",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by ()(100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$k8s_instances\"}[$__rate_interval]))) )"
      }
     ]
    },
    {
     "title": "Sys Load - k8s",
     "type": "stat",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(max_over_time(node_load1{instance=~\"$k8s_instances\"}[5m])) * 100 / \nmax(count by (instance) (count by (cpu, instance) (node_cpu_seconds_total{instance=~\"$k8s_instances\"})))"
      }
     ]
    },
    {
     "title": "RAM Used - k8s",
     "type": "stat",
     "description": "Non available RAM memory",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () ((1 - (node_memory_MemAvailable_bytes{instance=~\"$k8s_instances\"} / node_memory_MemTotal_bytes{instance=~\"$k8s_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "SWAP Used - k8s",
     "type": "stat",
     "description": "Used Swap",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (((node_memory_SwapTotal_bytes{instance=~\"$k8s_instances\"} - node_memory_SwapFree_bytes{instance=~\"$k8s_instances\"}) / (node_memory_SwapTotal_bytes{instance=~\"$k8s_instances\"})) * 100)"
      }
     ]
    },
    {
     "title": "Root FS Used  - ObjectStore",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by () (\n  100 - (node_filesystem_avail_bytes{instance=~\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=~\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"}\n)",
       "legendFormat": " "
      }
     ]
    }
   ]
  },
  {
   "title": "ObjectStore",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy - $ceph_instances",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 5 },
     "repeat": "ceph_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$ceph_instances\"}[$__rate_interval]))) ",
       "legendFormat": "Ceph1"
      }
     ]
    },
    {
     "title": "Sys Load - $ceph_instances",
     "type": "stat",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 8 },
     "repeat": "ceph_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=~\"$ceph_instances\"}) * 100 / count(count(node_cpu_seconds_total{instance=~\"$ceph_instances\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used - $ceph_instances",
     "type": "stat",
     "description": "Non available RAM memory ",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 11 },
     "repeat": "ceph_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$ceph_instances\"} / node_memory_MemTotal_bytes{instance=\"$ceph_instances\"})) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used - $ceph_instances",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 14 },
     "repeat": "ceph_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$ceph_instances\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "k8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy - $k8s_instances",
     "type": "stat",
     "description": "Busy state of all CPU cores together",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
     "repeat": "k8s_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", instance=\"$k8s_instances\"}[$__rate_interval]))) ",
       "legendFormat": "Ceph1"
      }
     ]
    },
    {
     "title": "Sys Load - $k8s_instances",
     "type": "stat",
     "description": "System load  over all CPU cores together",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 9 },
     "repeat": "k8s_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "scalar(node_load1{instance=~\"$k8s_instances\"}) * 100 / count(count(node_cpu_seconds_total{instance=~\"$k8s_instances\"}) by (cpu))"
      }
     ]
    },
    {
     "title": "RAM Used - $k8s_instances",
     "type": "stat",
     "description": "Non available RAM memory ",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
     "repeat": "k8s_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{instance=\"$k8s_instances\"} / node_memory_MemTotal_bytes{instance=\"$k8s_instances\"})) * 100"
      }
     ]
    },
    {
     "title": "Root FS Used - $k8s_instances",
     "type": "stat",
     "description": "Used Root FS",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 15 },
     "repeat": "k8s_instances",
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$k8s_instances\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$k8s_instances\",mountpoint=\"/\",fstype!=\"rootfs\"})"
      }
     ]
    }
   ]
  }
 ]
}