apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privacyidea-postgres-pvc
  namespace: trinityid
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 50Gi
