apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privacyidea-data-pvc
  namespace: trinityid
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi
