---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- instrumentations.opentelemetry.io.yaml
- opampbridges.opentelemetry.io.yaml
- opentelemetrycollectors.opentelemetry.io.yaml
- targetallocators.opentelemetry.io.yaml
