---
apiVersion: v1
kind: Service
metadata:
  name: python-docs-service
  namespace: n8n
spec:
  selector:
    app: python-docs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP