apiVersion: v1
kind: Secret
metadata:
  name: openldap-secrets
  namespace: trinityid
type: Opaque
stringData:
  LDAP_ADMIN_PASSWORD: "changeme"  # MUST be changed in actual deployment
  LDAP_REPLICATION_PASSWORD: "replication-changeme"  # MUST be changed
  LDAP_CONFIG_PASSWORD: "config-changeme"  # MUST be changed
