apiVersion: v1
kind: Service
metadata:
  name: openldap-headless
  namespace: trinityid
  labels:
    app: openldap
    component: ldap
spec:
  clusterIP: None  # Headless service for StatefulSet
  selector:
    app: openldap
  ports:
    - name: ldap
      port: 389
      protocol: TCP
    - name: ldaps
      port: 636
      protocol: TCP
    - name: replication
      port: 9010
      protocol: TCP
