---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ollama-pv
  namespace: ollama
spec:
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ollama-expandable
  nfs:
    path: /data/nfs/ollama/ollama/0
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: openwebui-pv
  namespace: ollama
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: openwebui-expandable
  nfs:
    path: /data/nfs/ollama/openwebui/0
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1