---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
  namespace: ollama
spec:
  storageClassName: ollama-expandable
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openwebui-pvc
  namespace: ollama
spec:
  storageClassName: openwebui-expandable
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
