---
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ollama
resources:
  - 00-namespace.yaml
  - 00-storage-class.yaml
  - 01-pv.yaml
  - 02-pvc.yaml
  - 03-deployment.yaml
  - 04-service.yaml
  - 05-ingress.yaml
  - 06-ingress-middleware.yaml
  - 10-certificate.yaml