---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: n8n-k8s-tommahs-nl-tls
  namespace: n8n
spec:
  secretName: n8n-k8s-tommahs-nl-tls
  dnsNames:
    - n8n.k8s.tommahs.nl
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer