apiVersion: v1
kind: ConfigMap
metadata:
  name: init-data
  namespace: n8n
data:
  init-data.sh: |
    #!/bin/bash
    set -e;
    if [ -n "${POSTGRES_NON_ROOT_USER:-}" ] && [ -n "${POSTGRES_NON_ROOT_PASSWORD:-}" ]; then
      psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
        CREATE USER "${POSTGRES_NON_ROOT_USER}" WITH PASSWORD '${POSTGRES_NON_ROOT_PASSWORD}';
        CREATE SCHEMA IF NOT EXISTS n8n_schema AUTHORIZATION "${POSTGRES_NON_ROOT_USER}";
        GRANT USAGE, CREATE ON SCHEMA n8n_schema TO "${POSTGRES_NON_ROOT_USER}";
        GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA n8n_schema TO "${POSTGRES_NON_ROOT_USER}";
        GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA n8n_schema TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DEFAULT PRIVILEGES IN SCHEMA n8n_schema 
            GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "${POSTGRES_NON_ROOT_USER}";
        ALTER DEFAULT PRIVILEGES IN SCHEMA n8n_schema 
            GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO "${POSTGRES_NON_ROOT_USER}";

      EOSQL
    else
      echo "SETUP INFO: No Environment variables given!"
    fi
    echo "Configuring vector extension..."

    # Run the SQL command using environment variables
    PGPASSWORD="${POSTGRES_PASSWORD}" psql -U "${POSTGRES_USER}" -d "${POSTGRES_DB}" -h "localhost" -p "5432" -c "CREATE EXTENSION IF NOT EXISTS vector;"

    echo "Vector extension installed."