apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml.template: 
    global:
      resolve_timeout: 5m

    route:
      receiver: default

    receivers:
      - name: default
