apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  alertmanager.yaml: 
    global:
      resolve_timeout: 5m

    route:
      receiver: default

    receivers:
      - name: default
