---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: observability
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`alertmanager.example.com`)
      priority: 10
      middlewares:
        - name: redirect-to-https
      services:
        - name: alertmanager
          namespace: observability
          passHostHeader: true
          port: 80
          responseForwarding:
            flushInterval: 1ms
  tls:
    secretName: alertmanager-tls

