apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: observability
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`alertmanager.example.com`)
      priority: 10
      middlewares:
        - name: redirect-to-https
      services:
        - name: alertmanager
          namespace: observability
          port: 80
          passHostHeader: true
  tls:
    secretName: alertmanager-tls
