resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingressroute.yaml
  - ingress-middlewares.yaml
  - secret.yaml

generatorOptions:
  disableNameSuffixHash: true

replacements:
  - source:
      kind: Secret
      name: alertmanager-secret
      fieldPath: stringData.ALERTMANAGER_ENDPOINT
    targets:
      - select:
          kind: IngressRoute
          name: alertmanager
        fieldPaths:
          - spec.routes.0.match
        options:
          delimiter: "`"
          index: 1

  - source:
      kind: Secret
      name: alertmanager-secret
      fieldPath: stringData.ALERTMANAGER_EXTERNAL_URL
    targets:
      - select:
          kind: Deployment
          name: alertmanager
        fieldPaths:
          - spec.template.spec.containers.0.args.2
        options:
          delimiter: "="
          index: 1
