---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: loki-tls
  namespace: observability
spec:
  secretName: loki-tls
  dnsNames:
    - loki.example.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer