apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
data:
  loki.yaml.template: |
    auth_enabled: false

    server:
      http_listen_port: 3100
      grpc_listen_port: 9095

    common:
      path_prefix: /loki
      replication_factor: 3
      storage:
        s3:
          endpoint: ${S3_ENDPOINT}
          insecure: ${S3_SECURE_CONNECT}
          bucketnames: ${LOKI_S3_BUCKET_NAME}
          access_key_id: ${S3_ACCESS_KEY}
          secret_access_key: ${S3_SECRET_KEY}
          s3forcepathstyle: ${S3_PATH_STYLE}
      compactor_address: loki-compactor
      ring:
        kvstore:
          store: memberlist


    schema_config:
      configs:
        - from: 2023-07-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    compactor:
      working_directory: /tmp/loki/compactor
      shared_store: s3
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      compaction_interval: 10m

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
      max_query_series: 10000

    ruler:
      storage:
        type: local
        local:
          directory: /tmp/loki/rules
      rule_path: /tmp/loki/rules
      alertmanager_url: http://alertmanager:9093
      ring:
        kvstore:
          store: memberlist

    distributor:
      ring:
        kvstore:
          store: memberlist

    ingester_client:
      grpc_client_config:
        max_recv_msg_size: 104857600
        max_send_msg_size: 104857600

    frontend:
      log_queries_longer_than: 5s
      compress_responses: true

    frontend_worker:
      frontend_address: loki-query-frontend:9095

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 3
      chunk_idle_period: 1h
      chunk_block_size: 262144
      chunk_target_size: 1536000
      chunk_retain_period: 30s
      max_transfer_retries: 0
      wal:
        enabled: true
        dir: /tmp/loki/wal

    memberlist:
      join_members:
        - loki-memberlist

    query_range:
      align_queries_with_step: true
      cache_results: true
      results_cache:
        cache:
          enable_fifocache: true
          fifocache:
            max_size_items: 1024
            validity: 24h
