apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-distributor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki
      component: distributor
  template:
    metadata:
      labels:
        app: loki
        component: distributor
    spec:
      initContainers:
      - name: config-merge
        image: busybox:1.36
        command: ["/bin/sh", "-c"]
        args:
          - |
            for f in /lgtm-s3-secrets/*; do export $(basename $f)=$(cat $f); done
            for f in /loki-secrets/*; do export $(basename $f)=$(cat $f); done
            
            # Use envsubst to replace placeholders in /etc/loki/loki.yaml.template and output to a writable directory
            cat /etc/loki/loki.yaml.template | envsubst > /etc/loki/merged-loki.yaml
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
        - name: lgtm-s3-secrets
          mountPath: /lgtm-s3-secrets
        - name: loki-secrets
          mountPath: /loki-secrets
        - name: merged-config
          mountPath: /etc/loki/merged-loki.yaml
          subPath: loki.yaml # We use subPath to ensure the file name stays consistent

      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
        - -target=distributor
        - -config.file=/etc/loki/merged-loki.yaml
        - -config.expand-env=true
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9095
          name: grpc
        volumeMounts:
          - name: loki-config
            mountPath: /etc/loki
          - name: lgtm-s3-secrets
            mountPath: /lgtm-s3-secrets
          - name: loki-secrets
            mountPath: /loki-secrets
          - name: merged-config
            mountPath: /etc/loki
      volumes:
        - name: loki-config
          configMap:
            name: loki-config
        - name: lgtm-s3-secrets
          secret:
            secretName: lgtm-s3-secret
        - name: loki-secrets
          secret:
            secretName: loki-secret
        - name: merged-config
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: loki-distributor
spec:
  ports:
  - port: 3100
    name: http
  - port: 9095
    name: grpc
  selector:
    app: loki
    component: distributor