# loki/gateway.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loki
      component: gateway
  template:
    metadata:
      labels:
        app: loki
        component: gateway
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3-alpine
        ports:
        - containerPort: 3100
          name: http
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: loki-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-gateway
data:
  nginx.conf: |
    server {
      listen 3100;
      
      location = / {
        return 200 'Loki Gateway';
      }

      location = /loki/api/v1/push {
        proxy_pass http://loki-distributor:3100$request_uri;
      }
      
      location ~ /loki/api/.* {
        proxy_pass http://loki-query-frontend:3100$request_uri;
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: loki-gateway
spec:
  ports:
  - port: 3100
    name: http
  selector:
    app: loki
    component: gateway