apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: loki-index-gateway
spec:
  replicas: 2
  serviceName: loki-index-gateway
  selector:
    matchLabels:
      app: loki
      component: index-gateway
  template:
    metadata:
      labels:
        app: loki
        component: index-gateway
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.9.0
        args:
        - -target=index-gateway
        - -config.file=/etc/loki/loki.yaml  # Use config with S3 backend
        ports:
        - containerPort: 3100
          name: http
        - containerPort: 9095
          name: grpc
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki
          subPath: loki.yaml  # Mount only the necessary config file
      volumes:
      - name: loki-config
        configMap:
          name: loki-config
---
apiVersion: v1
kind: Service
metadata:
  name: loki-index-gateway
spec:
  ports:
  - port: 3100
    name: http
  - port: 9095
    name: grpc
  selector:
    app: loki
    component: index-gateway
