{
 "title": "Traefik Ingress K8s",
 "description": "This dashboard is inspired by https://grafana.com/grafana/dashboards/17347-traefik-official-kubernetes-dashboard/",
 "tags": [
  "traefik",
  "k8s",
  "ingress"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(traefik_service_requests_total,service)"
    }
   },
   {
    "name": "entrypoint",
    "label": "Entrypoint",
    "query": {
     "query": "label_values(traefik_open_connections,entrypoint)"
    }
   },
   { "name": "DS_LOGS", "label": "Log datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traefik Instances",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(traefik_config_reloads_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per Entrypoint",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 7, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total{entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (entrypoint)",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  },
  {
   "title": "Apdex score",
   "type": "timeseries",
   "description": "https://medium.com/@tristan_96324/prometheus-apdex-alerting-d17a065e39d0",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "(sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"0.3\",code=\"200\",entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (method) + \n sum(rate(traefik_entrypoint_request_duration_seconds_bucket{le=\"1.2\",code=\"200\",entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (method)) / 2 / \n sum(rate(traefik_entrypoint_request_duration_seconds_count{code=\"200\",entrypoint=~\"$entrypoint\"}[$__rate_interval])) by (method)\n",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Http Code ",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) by (method, code)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Http Code aggregated",
   "type": "piechart",
   "description": "Mean Distribution",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(\n  label_replace(\n    rate(traefik_service_requests_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval]),\n    \"code_class\", \"${1}xx\", \"code\", \"(.)[0-9]*\"\n  )\n) by (method, code_class)",
     "legendFormat": "{{code_class}}[{{method}}]"
    }
   ]
  },
  {
   "title": "Most requested services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        sum by (service,code) \n          (rate(traefik_service_requests_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) > 0,\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)",
     "legendFormat": "[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "Top slow services",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(15,\n    label_replace(\n        traefik_service_request_duration_seconds_sum{service=~\"$ingress.*\",protocol=\"http\"} / \n          traefik_service_request_duration_seconds_count{service=~\"$ingress.*\",protocol=\"http\"},\n        \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)\n\n",
     "legendFormat": "{{method}}[{{code}}] on {{service}}"
    }
   ]
  },
  {
   "title": "HTTP details - General",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "2xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1279 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code=~\"2..\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "5xx",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1279 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code=~\"5..\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "Other codes over $interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1279 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code!~\"2..|5..\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
       "legendFormat": "{{method}}[{{code}}]"
      }
     ]
    },
    {
     "title": "Requests Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1287 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (method) \n  (rate(traefik_service_requests_bytes_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Responses Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1287 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(15,\n  sum by (method) \n  (rate(traefik_service_responses_bytes_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Connections per Entrypoint",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1295 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(traefik_open_connections{entrypoint=~\"$entrypoint\"}) by (entrypoint)\n",
       "legendFormat": "{{entrypoint}}"
      }
     ]
    }
   ]
  },
  { "title": "HTTP details - $ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "ingress" },
  {
   "title": "2xx on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n\n  label_replace(\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code=~\"2..\",protocol=\"http\"}[$__rate_interval])) > 0, \n    \"service\", \"$1\", \"service\", \"([^@]+)@.*\")\n)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "5xx on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code=~\"5..\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Other codes on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "topk(15,\n  sum by (method,code) \n  (rate(traefik_service_requests_total{service=~\"$ingress.*\",code!~\"2..|5..\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
     "legendFormat": "{{method}}[{{code}}]"
    }
   ]
  },
  {
   "title": "Requests Size  on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n  sum by (method) \n  (rate(traefik_service_requests_bytes_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Responses Size on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(15,\n  sum by (method) \n  (rate(traefik_service_responses_bytes_total{service=~\"$ingress.*\",protocol=\"http\"}[$__rate_interval])) > 0\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Connections per Entrypoint on $ingress",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(traefik_open_connections{entrypoint=~\"$entrypoint\"}) by (entrypoint)\n",
     "legendFormat": "{{entrypoint}}"
    }
   ]
  }
 ]
}