{
 "title": "Cert-manager-Kubernetes",
 "description": "The dashboard gives an overview of the SSL certs managed by cert-manager in Kubernetes",
 "tags": [
  "k8s",
  "cert-manager"
 ],
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status,namespace)"
    }
   },
   {
    "name": "issuer_kind",
    "label": "Issuer Kind",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{namespace=~\"$namespace\"},issuer_kind)"
    }
   },
   {
    "name": "issuer_name",
    "label": "issuer name",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{namespace=~\"$namespace\", issuer_kind=~\"$issuer_kind\"},issuer_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Valid Certificates",
   "type": "stat",
   "description": "The number if available certificates",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_ready_status{condition=\"True\", namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"})"
    }
   ]
  },
  {
   "title": "Expiring Certificates",
   "type": "stat",
   "description": "The number of certificates that will expire within the next 14 days",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"} < (time()+(14*24*3600)))"
    }
   ]
  },
  {
   "title": "Total ACME Requests",
   "type": "stat",
   "description": "Total number of HTTP requests, based on the selected time range",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{namespace=~\"$namespace\", issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Time to Expiration (<45 days)",
   "type": "bargauge",
   "description": "Time before the certificates expire. Only shows certificates expiring within 45 days",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"} - time()) < 45 * (24*3600)"
    }
   ]
  },
  {
   "title": "Time to Automatic Renewal (<45 days)",
   "type": "bargauge",
   "description": "Time before the certificates are automatically renewed",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(certmanager_certificate_renewal_timestamp_seconds{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"} - time()) < 45 * (24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Time to Expiration",
   "type": "timeseries",
   "description": "Time before the certificates expire",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "targets": [
    {
     "expr": "(certmanager_certificate_expiration_timestamp_seconds{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"} - time())/(24*3600)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Certificate Renewal Events",
   "type": "timeseries",
   "description": "Displays the timestamp of a renewal, based on the expiration time changing",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "changes(certmanager_certificate_renewal_timestamp_seconds{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"}[15m]) > 0"
    }
   ]
  },
  {
   "title": "ACME Requests by Cluster",
   "type": "barchart",
   "description": "Total number of HTTP requests, based on the selected range",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sort_desc(sum by (namespace)(increase(certmanager_http_acme_client_request_count{namespace=~\"$namespace\",issuer_kind=~\"$issuer_kind\", issuer_name=~\"$issuer_name\"}[$__rate_interval]))) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}