---
# This file is located at: opentelemetry-collector/ceph/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config-ceph
  namespace: observability
data:
  config.yaml: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'ceph-metrics'
              static_configs:
                - targets:
                  - ${CEPH_METRICS_TARGET}
              scrape_interval: 15s  # Reduced from 30s
              scrape_timeout: 10s   # Added explicit timeout
              metrics_path: /metrics

    processors:
      batch:
        timeout: 5s              # Reduced from 10s for lower latency
        send_batch_max_size: 512 # Reduced from 1024 to prevent large batches
        send_batch_size: 256     # Added to trigger batches earlier

      resource:
        attributes:
          - key: cluster
            value: main-cluster
            action: upsert
          - key: collector.name
            value: metrics-scraper
            action: upsert

      # Memory limiter to prevent OOM
      memory_limiter:
        limit_mib: 256
        spike_limit_mib: 64
        check_interval: 1s

    exporters:
      otlp:
        endpoint: otel-gateway-collector:4317
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 2
          queue_size: 100

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp]

      extensions: []  # No extensions needed