# common/s3-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: monitoring
type: Opaque
stringData:
  access_key: your-ceph-s3-access-key
  secret_key: your-ceph-s3-secret-key