apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  image: otel/opentelemetry-collector-contrib:latest 
  mode: daemonset
  volumeMounts:
    - mountPath: /etc/otel/certs/kubelet-ca.crt
      name: kubelet-ca-cert
      readOnly: true
  volumes:
    - name: kubelet-ca-cert
      hostPath:
        path: /var/lib/kubelet/pki/kubelet.crt  # Path to specific CA file on host
        type: File
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  config: 
    receivers:
      kubeletstats:
        collection_interval: 20s
        auth_type: "serviceAccount"
        ca_file: "/etc/otel/certs/kubelet-ca.crt"
        endpoint: "${K8S_NODE_NAME}:10250"

      # For application metrics (Prometheus format)
      prometheus:
        config:
          scrape_configs:
            - job_name: 'kubernetes-pods'
              kubernetes_sd_configs:
                - role: pod
              relabel_configs:
                - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
                  action: keep
                  regex: true
      
      # For logs
      filelog:
        include: [ /var/log/pods/*/*.log ]
        start_at: end
        include_file_path: true
        operators:
          - type: json_parser
            
      # For traces
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch: {}
      memory_limiter:
        check_interval: 1s
        limit_mib: 1000
      k8sattributes:
        auth_type: "serviceAccount"
        passthrough: false
        extract:
          metadata:
            - k8s.pod.name
            - k8s.pod.uid
            - k8s.deployment.name
            - k8s.namespace.name
            - k8s.node.name
            - k8s.container.name

    exporters:
      # For metrics to Mimir
      prometheusremotewrite:
        endpoint: "http://mimir-distributor.observability.svc.cluster.local:8080/api/v1/push"
        tls:
          insecure: true
      
      # For logs to Loki
      otlphttp:
        endpoint: "http://loki-gateway.observability.svc.cluster.local:3100/otlp/v1/logs"
      # For traces to Tempo
      otlp:
        endpoint: tempo-distributor.observability.svc.cluster.local:4317
        tls:
          insecure: true

    service:
      pipelines:
        metrics:
          receivers: [kubeletstats, prometheus]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [prometheusremotewrite]
        logs:
          receivers: [filelog]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlphttp]
        traces:
          receivers: [otlp]
          processors: [memory_limiter, k8sattributes, batch]
          exporters: [otlp]