apiVersion: v1
kind: Service
metadata:
  labels:
    service: n8n
  name: n8n
  namespace: n8n
spec:
  selector:
    service: n8n
  # type: LoadBalancer
  ports:
    - protocol: TCP
      name: "5678"
      port: 5678
      targetPort: 5678