# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - grafana/
  - loki/
  # - mimir/
  # - tempo/
  - common/