# Grafana service configuration
service:
  type: ClusterIP

# Admin credentials
adminUser: admin
adminPassword: your-secure-password  # Change this!

# Disable default ingress as we'll use Traefik IngressRoute
ingress:
  enabled: false

# Basic persistence
persistence:
  enabled: true
  size: 10Gi

# Traefik IngressRoute configuration
ingressRoute:
  dashboard:
    # This will create a Traefik IngressRoute CRD
    enabled: true
    # Use both HTTP and HTTPS endpoints
    entryPoints: ["web", "websecure"]
    # Your domain configuration
    match: Host(`grafana.example.com`)  # Replace with your domain
    # Point to the Grafana service
    service:
      name: grafana
      port: 80
