---
apiVersion: v1
kind: Secret
metadata:
  namespace: owncloud
  name: owncloud-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: changeme
  MYSQL_DATABASE: owncloud
  MYSQL_USER: owncloud
  MYSQL_PASSWORD: changeme
  NFS_PATH: ExposedNFSPathOnServer
  NFS_PATH_DB: ExposedNFSPathDatabaseOnServer
  NFS_SERVER: IPorDomainNameOfServer
  OWNCLOUD_DB_TYPE: mysql
  OWNCLOUD_DB_HOST: mariadb
  OWNCLOUD_REDIS_HOST: redis
  OWNCLOUD_REDIS_PORT: 6379
  OWNCLOUD_ENDPOINT: cloud.example.com
