---
apiVersion: v1
kind: Service
metadata:
  name: pathfinderwiki-mariadb-service
  namespace: pathfinderwiki
spec:
  selector:
    app: pathfinderwiki-mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
