---
# 01-cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-server
rules:
- apiGroups: [""]
  resources:
    - "namespaces"
    - "pods"
    - "services"
    - "secrets"
    - "serviceaccounts"
  verbs: ["get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources:
    - "roles"
    - "rolebindings"
    - "clusterroles"
    - "clusterrolebindings"
  verbs: ["get", "list", "watch"]
- apiGroups: ["authentication.k8s.io"]
  resources:
    - "tokenreviews"
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
    - "subjectaccessreviews"
  verbs: ["create"]