---
# Service to expose Nginx internally
apiVersion: v1
kind: Service
metadata:
  name: pathfinderwiki-nginx-service
  namespace: pathfinderwiki
spec:
  selector:
    app: pathfinderwiki-nginx
  ports:
    - port: 80
      targetPort: 80