---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config-node-template
data:
  config.yaml.template: |
    receivers:
      prometheus:
        config:
          scrape_configs:
            - job_name: 'node-metrics'
              static_configs:
                - targets:
                  __TARGETS__
              relabel_configs:
                - source_labels: [__address__]
                  regex: "([^:]+):\\d+"
                  target_label: instance
                  replacement: "$1"
              scrape_interval: 15s
              scrape_timeout: 10s
              metrics_path: /metrics
    processors:
      batch:
        timeout: 5s
        send_batch_max_size: 512
        send_batch_size: 256
      resource:
        attributes:
          - key: cluster
            value: main-cluster
            action: upsert
          - key: collector.name
            value: metrics-scraper
            action: upsert
      memory_limiter:
        limit_mib: 256
        spike_limit_mib: 64
        check_interval: 1s
    exporters:
      otlp:
        endpoint: otel-gateway-collector:4317
        tls:
          insecure: true
        retry_on_failure:
          enabled: true
          initial_interval: 1s
          max_interval: 30s
          max_elapsed_time: 300s
        sending_queue:
          enabled: true
          num_consumers: 2
          queue_size: 100

    service:
      pipelines:
        metrics:
          receivers: [prometheus]
          processors: [memory_limiter, batch, resource]
          exporters: [otlp]
      
      extensions: []
