{
 "title": "Ceph - Cluster",
 "description": "Ceph Cluster overview.\r\n",
 "tags": [
  "ceph",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CLUSTER STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_health_status{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Write Throughput",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read Throughput",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Cluster Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Available Capacity",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{})/ceph_cluster_total_bytes{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Number of Objects",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_pool_objects{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bytes Written",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      { "expr": "sum(ceph_osd_op_w_in_bytes{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Bytes Read",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "delta" ] } },
     "targets": [
      { "expr": "sum(ceph_osd_op_r_out_bytes{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Alerts starting with Ceph",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}) OR vector(0)"
      }
     ]
    },
    {
     "title": "Write IOPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 3, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read IOPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 6, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_r{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Used Capacity",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ceph_cluster_total_used_bytes{}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Difference",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 15, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      { "expr": "sum(ceph_pool_objects)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Mon Session Num",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 18, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_mon_num_sessions{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Monitors In Quorum",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 21, "y": 127 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_mon_quorum_status{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "OSD STATE",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSDs OUT",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 0, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_osd_up{}) - count(ceph_osd_in{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSDs DOWN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "count(ceph_osd_up{} == 0.0) OR vector(0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSDs UP",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_osd_up{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OSDs IN",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "sum(ceph_osd_in{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Avg PGs",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "avg(ceph_osd_numpg{})", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Avg Apply Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 10, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(ceph_osd_apply_latency_ms{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Commit Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 13, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(ceph_osd_commit_latency_ms{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg Op Write Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 16, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg  Op Read Latency",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 19, "y": 131 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[5m])/rate(ceph_osd_op_r_latency_count{}[5m]) >= 0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Alerts starting with Ceph",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ALERTS{alertstate=\"firing\",alertname=~\"^Ceph.+\"}"
      }
     ]
    },
    {
     "title": "Top Sluggish OSD's",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(5,sort_desc(ceph_osd_apply_latency_ms{} + ceph_osd_commit_latency_ms{}))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Down OSD's",
     "type": "table",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "ceph_osd_up{} == 0", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  {
   "title": "Ceph Versions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ceph OSD Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_osd_metadata{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ceph Mon Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mon_metadata{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ceph MDS Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_mds_metadata{})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Ceph RGW Versions",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count by (ceph_version)(ceph_rgw_metadata{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "CLUSTER",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Capacity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      { "expr": "ceph_cluster_total_bytes{}", "legendFormat": "Total cluster bytes" },
      {
       "expr": "ceph_cluster_total_bytes{}-ceph_cluster_total_used_bytes{}",
       "legendFormat": "Available cluster bytes"
      },
      {
       "expr": "ceph_cluster_total_used_bytes{}",
       "legendFormat": "Used cluster bytes"
      }
     ]
    },
    {
     "title": "IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w{}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_op_w_in_bytes{}[5m]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(irate(ceph_osd_op_r_out_bytes{}[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pool Used Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_bytes_used{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool RAW Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_avail_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "available raw - {{name}}"
      },
      {
       "expr": "(ceph_pool_stored_raw{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "stored raw - {{name}}"
      }
     ]
    },
    {
     "title": "Objects Per Pool",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ceph_pool_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Quota Bytes",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "(ceph_pool_quota_bytes{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Pool Objects Quota",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(ceph_pool_quota_objects{}) *on (pool_id) group_left(name)(ceph_pool_metadata{})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "OSD Type Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(ceph_bluestore_kv_commit_lat_count{})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "OBJECTS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Objects in the Cluster",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 6, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pool_objects)", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "PGs State",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 8, "x": 6, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pg_active{})", "legendFormat": "active" },
      { "expr": "sum(ceph_pg_clean{})", "legendFormat": "clean" },
      { "expr": "sum(ceph_pg_peering{})", "legendFormat": "peering" },
      { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "degraded" },
      { "expr": "sum(ceph_pg_stale{})", "legendFormat": "stale" },
      { "expr": "sum(ceph_unclean_pgs{})", "legendFormat": "unclean" },
      { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "undersized" },
      { "expr": "sum(ceph_pg_incomplete{})", "legendFormat": "incomplete" },
      { "expr": "sum(ceph_pg_forced_backfill{})", "legendFormat": "forced_backfill" },
      { "expr": "sum(ceph_pg_inconsistent{})", "legendFormat": "inconsistent" },
      { "expr": "sum(ceph_pg_forced_recover{})", "legendFormat": "forced_recover" },
      { "expr": "sum(ceph_pg_creating{})", "legendFormat": "creating" },
      { "expr": "sum(ceph_pg_wait_backfill{})", "legendFormat": "wait_backfill" },
      { "expr": "sum(ceph_pg_deep{})", "legendFormat": "deep" },
      { "expr": "sum(ceph_pg_scrubbing{})", "legendFormat": "scrubbing" },
      { "expr": "sum(ceph_pg_recovering{})", "legendFormat": "recovering" },
      { "expr": "sum(ceph_pg_repair{})", "legendFormat": "repair" },
      { "expr": "sum(ceph_pg_down{})", "legendFormat": "down" },
      { "expr": "sum(ceph_pg_peered{})", "legendFormat": "peered" },
      { "expr": "sum(ceph_pg_backfill{})", "legendFormat": "backfill" },
      {
       "expr": "sum(ceph_pg_backfill_toofull{})",
       "legendFormat": "backfill_toofull"
      },
      { "expr": "sum(ceph_pg_remapped{})", "legendFormat": "remapped" }
     ]
    },
    {
     "title": "Stuck PGs",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "sum(ceph_pg_degraded{})", "legendFormat": "degraded" },
      { "expr": "sum(ceph_pg_stale{})", "legendFormat": "stale" },
      { "expr": "sum(ceph_pg_undersized{})", "legendFormat": "undersized" }
     ]
    },
    {
     "title": "Recovery Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(irate(ceph_osd_recovery_ops{}[$interval]))",
       "legendFormat": "Ops"
      }
     ]
    }
   ]
  },
  {
   "title": "LATENCY",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "OSD Apply Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      { "expr": "ceph_osd_apply_latency_ms{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OSD Commit Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      { "expr": "ceph_osd_commit_latency_ms{}", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "OSD Read Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "OSD Write Op Latency Distribution",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Avg OSD  Op  Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(rate(ceph_osd_op_r_latency_sum{}[5m]) / rate(ceph_osd_op_r_latency_count{}[5m]) >= 0)",
       "legendFormat": "Read"
      },
      {
       "expr": "avg(rate(ceph_osd_op_w_latency_sum{}[5m]) / rate(ceph_osd_op_w_latency_count{}[5m]) >= 0)",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "AVG OSD Apply + Commit Latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(ceph_osd_apply_latency_ms{})",
       "legendFormat": "Apply"
      },
      {
       "expr": "avg(ceph_osd_commit_latency_ms{})",
       "legendFormat": "Commit"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Statistics (NodeExporter)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "node_memory_Active_anon_bytes{}",
       "legendFormat": "{{instance}}"
      },
      {
       "direction": "backward",
       "expr": "sum(node_memory_Active_anon_bytes{})",
       "legendFormat": "Cluster Memory Usage"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "avg by(instance)(irate(node_cpu_seconds_total{job='node',mode!=\"idle\"}[$interval])) * 100",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node Out",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_read_bytes_total{}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Node In",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum by (instance)(irate(node_disk_written_bytes_total{}[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Free Space in root filesystem",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "(node_filesystem_free_bytes{ mountpoint='/', device != 'rootfs'})*100 / (node_filesystem_size_bytes{ mountpoint='/', device != 'rootfs'})",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}