--- 
# values.yaml for Cilium

# Enable kube-proxy replacement
kubeProxyReplacement: true
# Kubernetes Service Host and Port
k8sServiceHost: k8s.tommahs.nl
k8sServicePort: 6443

# IPAM Mode
ipam:
  mode: kubernetes

# Enable Envoy integration (if applicable)
envoy:
  enabled: true

# CNI chaining mode - empty means no chaining (assuming it's left empty as in your command)
cni:
  chainingMode: ""

# Enable Hubble and its components
hubble:
  enabled: true
  relay:
    enabled: true
    api:
      addr: "0.0.0.0:4244"
  ui:
    enabled: true
    port: 8081
    auth:
      anonymous:
        enabled: true

