---
# This file is located at: opentelemetry-collector/ceph/deployment.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
- secret.yaml
- configmap.yaml
- deployment.yaml