# grafana/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  grafana.ini: |
    [server]
    root_url = ${GF_ENDPOINT}
    
    [auth]
    disable_login_form = false
    
    [users]
    allow_sign_up = false
    
    [auth.anonymous]
    enabled = false
    
    [storage.s3]
    enabled = true
    bucket = ${GF_S3_BUCKET_NAME}
    endpoint = ${S3_ENDPOINT}
    path_style = ${S3_PATH_STYLE}
    access_key = ${S3_ACCESS_KEY}
    secret_key = ${S3_SECRET_KEY}
    insecure = ${S3_SECURE_CONNECT}
        
    [dashboards]
    default_home_dashboard_path = /var/lib/grafana/dashboards/default/home.json
    
    [dashboards.json]
    enabled = true
    path = /var/lib/grafana/dashboards
    
    [paths]
    data = /var/lib/grafana/data
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-server:9090
      access: proxy
      isDefault: true
      
  dashboard-provider.yaml: |
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/default
        foldersFromFilesStructure: true