# grafana/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - configmap-datasources
  - secret.yaml
  - pvc.yaml
  - pv.yaml

vars:
  - name: GF_ENDPOINT
    objref:
      kind: Secret
      name: lgtm-ingress-secret.yaml
      apiVersion: v1
    fieldref:
      fieldpath: data.GF_ENDPOINT
      
patchesStrategicMerge:
  - ingress-patch.yaml