# grafana/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - configmap.yaml
  - configmap-datasources.yaml
  - secret.yaml
  - pvc.yaml
  - pv.yaml

replacements:
  - source:
      kind: Secret
      name: lgtm-ingress-secret
      fieldPath: stringData.GF_ENDPOINT
    targets:
      - select:
          kind: Ingress
          name: grafana
        fieldPaths:
          - "spec.rules.0.host"
patches:
  - path: ingress-patch.yaml
