---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana
  namespace: observability
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: grafana
  nfs:
    path: /data/nfs/grafanalabs/grafana/
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1