---
# PVC for grafana persistent content
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: observability
spec:
  storageClassName: grafana-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi