apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-certificates-pv
  namespace: traefik
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: certificates
  nfs:
    path: /data/nfs/certificates
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1