---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pathfinderwiki-content-pv
  namespace: pathfinderwiki
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pathfinderwiki-content
  nfs:
    path: /data/nfs/pathfinderwiki/pathfinderwiki-content
    server: 192.168.122.1
  mountOptions:
    - hard
    - nfsvers=4.1